### PR TITLE
Fix and modify ReportTypes naming according to issue #100

### LINKED ISSUE #100: Report names are mixed after API change to BIR 1.1
After updating API to BIR 1.1 some report types are mixed in comparsion with BIR 1.0 based versions:

    public const REPORT_LOCALS_PHYSIC_PUBLIC = 'BIR11OsFizycznaPkd';
    public const REPORT_LOCAL_PHYSIC_PUBLIC = 'BIR11OsFizycznaListaJednLokalnych';
    public const REPORT_ACTIVITY_PHYSIC_PUBLIC = 'BIR11JednLokalnaOsFizycznej';

It should look like this:

    public const REPORT_LOCALS_PHYSIC_PUBLIC = 'BIR11OsFizycznaListaJednLokalnych';
    public const REPORT_LOCAL_PHYSIC_PUBLIC = 'BIR11JednLokalnaOsFizycznej';
    public const REPORT_ACTIVITY_PHYSIC_PUBLIC = 'BIR11OsFizycznaPkd';

In my opinion current report naming is not consistent and I will opt for a change in upcoming versions. We can keep current constants with deprecation mark and add a new set - my proposal is:

    public const REPORT_PHYSIC = 'BIR11OsFizycznaDaneOgolne';
    public const REPORT_PHYSIC_CEIDG = 'BIR11OsFizycznaDzialalnoscCeidg';
    public const REPORT_PHYSIC_AGRO = 'BIR11OsFizycznaDzialalnoscRolnicza';
    public const REPORT_PHYSIC_OTHER = 'BIR11OsFizycznaDzialalnoscPozostala';
    public const REPORT_PHYSIC_DELETED_BEFORE_20141108 = 'BIR11OsFizycznaDzialalnoscSkreslonaDo20141108';
    public const REPORT_PHYSIC_LOCALS = 'BIR11OsFizycznaListaJednLokalnych';
    public const REPORT_PHYSIC_LOCAL = 'BIR11JednLokalnaOsFizycznej';
    public const REPORT_PHYSIC_ACTIVITY = 'BIR11OsFizycznaPkd';
    public const REPORT_PHYSIC_LOCAL_ACTIVITY = 'BIR11JednLokalnaOsFizycznejPkd';
    public const REPORT_LAW = 'BIR11OsPrawna';
    public const REPORT_LAW_ACTIVITY = 'BIR11OsPrawnaPkd';
    public const REPORT_LAW_LOCALS = 'BIR11OsPrawnaListaJednLokalnych';
    public const REPORT_LAW_LOCAL = 'BIR11JednLokalnaOsPrawnej';
    public const REPORT_LAW_LOCAL_ACTIVITY = 'BIR11JednLokalnaOsPrawnejPkd';
    public const REPORT_LAW_PARTNERS = 'BIR11OsPrawnaSpCywilnaWspolnicy';
    public const REPORT_UNIT_TYPE = 'BIR11TypPodmiotu';

I can submit a PR for my proposal.

### PR DESCRIPTION
**Pull request by krzyc**
Fixes #100 and includes proposal for new report naming

### CODE REVIEW

**Comment by johnzuk** [comment]
There is a some strange problem with Scrutinizer - i will try to take a look on it tomorrow

**Comment by krzyc** [comment]
@johnzuk Any updates?

**Comment by johnzuk** [comment]
@krzyc all steps pass can you please take a look on my review ?

**Comment by johnzuk** [comment]
All pass i;ve only changed a message

**Pull request merged**
